FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git \
    cmake \
    g++ \
    make \
    libevent-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/edo9300/ygopro-server.git server

WORKDIR /app/server

RUN make

RUN mkdir -p /app/server/expansions

EXPOSE 27017

CMD ["./ygopro-server"]